create table if not exists import_file (
    id bigint generated by default as identity primary key,
    file_path varchar(2048) not null unique,
    file_name varchar(255) not null,
    group_name varchar(255),
    file_hash varchar(128) not null,
    model_name varchar(255) not null,
    target_db varchar(255),
    import_time timestamp not null
);

alter table import_file add column if not exists group_name varchar(255);

create table if not exists pdm_table (
    id bigint generated by default as identity primary key,
    import_file_id bigint not null,
    table_id_in_pdm varchar(255) not null,
    table_name varchar(255) not null,
    table_code varchar(255),
    table_comment varchar(2000),
    constraint fk_pdm_table_import
        foreign key (import_file_id) references import_file(id) on delete cascade
);

create table if not exists pdm_column (
    id bigint generated by default as identity primary key,
    table_id bigint not null,
    column_id_in_pdm varchar(255) not null,
    column_name varchar(255) not null,
    column_code varchar(255),
    data_type varchar(255),
    data_length integer,
    data_precision integer,
    data_scale integer,
    nullable_flag boolean not null,
    default_value varchar(2000),
    column_comment varchar(2000),
    pk_flag boolean not null,
    ordinal_position integer not null,
    constraint fk_pdm_column_table
        foreign key (table_id) references pdm_table(id) on delete cascade
);

create index if not exists idx_pdm_table_name on pdm_table(table_name);
create index if not exists idx_pdm_table_code on pdm_table(table_code);
create index if not exists idx_pdm_column_name on pdm_column(column_name);
create index if not exists idx_pdm_column_code on pdm_column(column_code);
